//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MetaLink { get; set; }
        public int DisplayNo { get; set; }
        public string IconImg { get; set; }
        public string FeatureImg { get; set; }
        public string Description { get; set; }
        public int ShowHome { get; set; }
        public int UserId { get; set; }
        public byte Status { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
