//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int PostId { get; set; }
        public string PostTitile { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string PostContent { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string FeatureImg { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte Status { get; set; }
    }
}
