//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string IconImg { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
        public int UserId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
